Change SOURCE_TYPE to FETCH_TYPE, git-archive format to tar.gz

diff --git a/lib/eupspkg/functions b/lib/eupspkg/functions
--- a/lib/eupspkg/functions
+++ b/lib/eupspkg/functions
@@ -57,24 +57,24 @@ default_create()
 	die_if_empty PRODUCT
 	die_if_empty VERSION
 
-	case "$SOURCE_TYPE" in
+	case "$FETCH_TYPE" in
 		git-archive)
-			[[ ! -z "$REPO_URL" ]] || { echo "pkgbuild error: $REPO_URL must be set for SOURCE_TYPE='$SOURCE_TYPE' type."; exit -1; }
-			git archive --format=tar --prefix "$FQNAME/" --remote="$REPO_URL" "$VERSION" ups/pkgbuild > /dev/null ||
+			[[ ! -z "$REPO_URL" ]] || { echo "pkgbuild error: $REPO_URL must be set for FETCH_TYPE='$FETCH_TYPE' type."; exit -1; }
+			git archive --format=tar.gz --prefix "$FQNAME/" --remote="$REPO_URL" "$VERSION" ups/pkgbuild > /dev/null ||
 				die "git-archive failed trying to check out $VERSION (do you need to tag it?)"
 			;;
 		tar.gz)
-			[[ ! -z "$REPO_URL" ]] || { echo "pkgbuild error: $REPO_URL must be set for SOURCE_TYPE='$SOURCE_TYPE' type."; exit -1; }
+			[[ ! -z "$REPO_URL" ]] || { echo "pkgbuild error: $REPO_URL must be set for FETCH_TYPE='$FETCH_TYPE' type."; exit -1; }
 			TARBALL="$FQNAME.tar.gz"
-			git archive --format=tar --prefix "$FQNAME/" --remote="$REPO_URL" "$VERSION" | gzip > "$TARBALL"
+			git archive --format=tar.gz --prefix "$FQNAME/" --remote="$REPO_URL" "$VERSION" > "$TARBALL"
 			append_pkginfo TARBALL "$TARBALL"
 			;;
 		inline|"")
-			[[ ! -z "$REPO_URL" ]] || { echo "pkgbuild error: $REPO_URL must be set for SOURCE_TYPE='$SOURCE_TYPE' type."; exit -1; }
-			git archive --format=tar --remote="$REPO_URL" "$VERSION" | tar xf - --exclude ups/pkgbuild --exclude ups/pkginfo
+			[[ ! -z "$REPO_URL" ]] || { echo "pkgbuild error: $REPO_URL must be set for FETCH_TYPE='$FETCH_TYPE' type."; exit -1; }
+			git archive --format=tar.gz --remote="$REPO_URL" "$VERSION" | tar xzf - --exclude ups/pkgbuild --exclude ups/pkginfo
 			;;
 		*)
-			echo "pkgbuild error: unknown source type SOURCE_TYPE='$SOURCE_TYPE'."; exit -1;
+			echo "pkgbuild error: unknown source type FETCH_TYPE='$FETCH_TYPE'."; exit -1;
 	esac
 }
 
@@ -93,9 +93,9 @@ default_fetch()
 	die_if_empty PRODUCT
 	die_if_empty VERSION
 
-	case "$SOURCE_TYPE" in
+	case "$FETCH_TYPE" in
 		git-archive)
-			git archive --format=tar  --remote="$REPO_URL" "$VERSION" | tar xf - --exclude ups/pkgbuild --exclude ups/pkginfo
+			git archive --format=tar.gz  --remote="$REPO_URL" "$VERSION" | tar xzf - --exclude ups/pkgbuild --exclude ups/pkginfo
 			;;
 		tar.gz)
 			tar xzf "$TARBALL" --strip-components 1 --exclude "$FQNAME/ups/pkgbuild" --exclude "$FQNAME/ups/pkginfo"
@@ -103,7 +103,7 @@ default_fetch()
 		inline|"")
 			;;
 		*)
-			echo "Unknown source '$SOURCE_TYPE'. Malformed archive?"; exit -1;
+			echo "Unknown source '$FETCH_TYPE'. Malformed archive?"; exit -1;
 			;;
 	esac
 }
@@ -248,7 +248,7 @@ shift $((OPTIND-1))
 #
 # Defaults the user (or pkginfo) can override
 #
-SOURCE_TYPE=			# [|inline|git-archive|tar.gz]
+FETCH_TYPE=			# [|inline|git-archive|tar.gz]. Usually passed in via command line (eups distrib create ... -S FETCH_TYPE=...)
 REPO_URL=			# URL to git repository
 MAKE_BUILD_TARGETS="all test"	# Targets for invocation of make in build phase
 MAKE_INSTALL_TARGETS="install"	# Targets for invocation of make in test phase
